"""Proposed memories on disk and the operator's decision on each.

Exports ``TYPES``, ``MIN_BODY``, ``MAX_BODY``, ``ProposalError``,
``proposals_dir``, ``render``, ``parse``, ``write_proposal``,
``list_proposals`` and ``decide``.

A proposal is ``meta_dir()/memory_proposals/<session>/<id>.md``: the memory
file exactly as it would land, frontmatter included. Ids are a millisecond
stamp plus random hex, created with O_EXCL, so they sort by age, are never
reused, and two writers cannot overwrite each other. A decision carries the
sha256 of the text the operator saw; a mismatch is a 409, so a stale card can
never approve text it did not show. Approve moves it into
the repo's memory directory (``context.memory.memory_dir``) as
``<type>_<snake_name>.md``. The write goes through the same PreToolUse hooks
a model's Write would meet, run explicitly with a ``Write`` payload, so the
memory schema gate in the operator's settings still judges it; a hook denial
leaves the proposal in place. MEMORY.md is then regenerated by a deployment's
``pipelines.memory_index`` when importable, else gains one index line.
Edit replaces the text and approves; reject deletes the proposal.
"""
from __future__ import annotations

import hashlib
import importlib
import os
import re
import secrets
import threading
import time
from pathlib import Path
from typing import Any, Callable

from coding_harness.context.memory import memory_dir
from coding_harness.core import paths
from coding_harness.security import audit

TYPES = frozenset({"feedback", "project", "reference", "user"})
MIN_BODY, MAX_BODY = 120, 4000
MAX_TEXT = 8000
_SID = re.compile(r"^[A-Za-z0-9_.-]{1,80}$")
_PID = re.compile(r"^[0-9]{13}-[0-9a-f]{8}$")
_CREATE_TRIES = 8
# GLOBAL-STATE: the last stamp handed out, so ids sort in creation order even
# when several proposals land in the same millisecond.
_STAMP = [0]
_STAMP_LOCK = threading.Lock()
_FM = re.compile(r"\A---\n(.*?)\n---\n?(.*)\Z", re.S)


class ProposalError(Exception):
    """A decision that cannot go through; ``status`` is the HTTP code to answer with."""

    def __init__(self, status: int, message: str) -> None:
        super().__init__(message)
        self.status = status


def proposals_dir(session_id: str) -> Path:
    """This session's proposal directory under the meta dir; the id is checked first."""
    if not _SID.match(session_id) or session_id in (".", ".."):
        raise ProposalError(400, "invalid session id")
    return paths.meta_dir() / "memory_proposals" / session_id


def render(cand: dict[str, str], provenance: str, session_id: str, turn: int) -> str:
    """The memory file text for one candidate, in the corpus frontmatter shape."""
    return (
        f"---\nname: {cand['name']}\ndescription: {cand['description']}\n"
        f"metadata:\n  type: {cand['type']}\n  provenance: {provenance}\n"
        f"  session: {session_id}\n  turn: {turn}\n---\n\n{cand['body'].strip()}\n"
    )


def parse(text: str) -> dict[str, str]:
    """name, description, type and body from a memory file; ProposalError(400) when malformed."""
    m = _FM.match(text.replace("\r\n", "\n"))
    if not m:
        raise ProposalError(400, "text must start with a --- frontmatter block")
    fields: dict[str, str] = {}
    for line in m.group(1).splitlines():
        key, sep, value = line.strip().partition(":")
        if sep and key in ("name", "description", "type"):
            fields[key] = value.strip().strip("'\"")
    body = m.group(2).strip()
    name, kind = fields.get("name", ""), fields.get("type", "")
    if not re.match(r"^[a-z0-9]+(?:-[a-z0-9]+)*$", name) or not 3 <= len(name) <= 60:
        raise ProposalError(400, "name must be a kebab-case slug of 3-60 chars")
    if kind not in TYPES:
        raise ProposalError(400, f"metadata.type must be one of {sorted(TYPES)}")
    if not fields.get("description") or not body:
        raise ProposalError(400, "description and body are required")
    return {"name": name, "description": fields["description"], "type": kind, "body": body}


def write_proposal(session_id: str, cand: dict[str, str], turn: int) -> dict[str, Any]:
    """Store one candidate as the next numbered proposal; the event payload."""
    folder = proposals_dir(session_id)
    folder.mkdir(parents=True, exist_ok=True)
    data = render(cand, "generated", session_id, turn).encode("utf-8")
    for _ in range(_CREATE_TRIES):
        pid = f"{_next_stamp():013d}-{secrets.token_hex(4)}"
        try:
            fd = os.open(folder / f"{pid}.md", os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        except FileExistsError:
            continue
        with os.fdopen(fd, "wb") as f:
            f.write(data)
        return {"id": pid, "name": cand["name"], "description": cand["description"],
                "type": cand["type"], "sha256": digest(data.decode("utf-8"))}
    raise ProposalError(500, "could not allocate a proposal id")


def _next_stamp() -> int:
    """Milliseconds since the epoch, strictly increasing within this process."""
    with _STAMP_LOCK:
        _STAMP[0] = max(time.time_ns() // 1_000_000, _STAMP[0] + 1)
        return _STAMP[0]


def digest(text: str) -> str:
    """The sha256 hex of ``text`` as UTF-8, the token a decision must echo."""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def list_proposals(session_id: str) -> list[dict[str, Any]]:
    """Every pending proposal for the session, oldest first, with its full text."""
    folder = proposals_dir(session_id)
    if not folder.is_dir():
        return []
    rows = []
    for path in sorted(folder.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        try:
            meta = parse(text)
        except ProposalError:
            continue
        rows.append({"id": path.stem, "name": meta["name"], "description": meta["description"],
                     "type": meta["type"], "text": text, "sha256": digest(text)})
    return rows


def _proposal_path(session_id: str, pid: str) -> Path:
    """The file for proposal ``pid``; 404 when it is gone."""
    if not isinstance(pid, str) or not _PID.match(pid):
        raise ProposalError(400, "body.id must be a proposal id")
    path = proposals_dir(session_id) / f"{pid}.md"
    if not path.is_file():
        raise ProposalError(404, f"no proposal {pid}")
    return path


def _update_index(folder: Path, cand: dict[str, str], filename: str) -> None:
    """Regenerate MEMORY.md with the deployment's indexer, else append one line."""
    try:
        indexer = importlib.import_module("pipelines.memory_index")
        indexer.main(["--dir", str(folder), "--write"])
        return
    except Exception:  # noqa: BLE001 the indexer is optional; the one-line append always works
        pass
    index = folder / "MEMORY.md"
    head = index.read_text(encoding="utf-8") if index.exists() else "# Memory index\n\n"
    if not head.endswith("\n"):
        head += "\n"
    line = f"- [{cand['name']}]({filename}) — {cand['description']}\n"
    tmp = index.with_suffix(".md.tmp")
    tmp.write_text(head + line, encoding="utf-8")
    os.replace(tmp, index)


def _land(session_id: str, text: str, cwd: str, hooks: Any) -> Path:
    """Write the approved memory through the PreToolUse hooks; the landed path."""
    cand = parse(text)
    folder = memory_dir(cwd)
    target = folder / f"{cand['type']}_{cand['name'].replace('-', '_')}.md"
    if target.exists():
        raise ProposalError(409, f"{target.name} already exists; edit the name first")
    args = {"file_path": str(target), "content": text}
    if hooks is not None:
        verdict = hooks.run("PreToolUse", tool_name="Write", tool_input=args)
        if not verdict.allowed:
            raise ProposalError(422, f"blocked by hook: {verdict.reason}")
    folder.mkdir(parents=True, exist_ok=True)
    tmp = target.with_suffix(".md.tmp")
    tmp.write_text(text, encoding="utf-8")
    os.replace(tmp, target)
    if hooks is not None:
        hooks.run("PostToolUse", tool_name="Write", tool_input=args, tool_output="written")
    _update_index(folder, cand, target.name)
    audit.append(session_id=session_id, tool="Write", args={"file_path": str(target)},
                 result="memory approved by operator", allowed=True,
                 sentinel_reason="operator_approved_memory", sentinel_path="fast")
    return target


def _edited(text: Any, session_id: str) -> str:
    """The operator's replacement text, re-stamped as operator provenance."""
    if not isinstance(text, str) or not text.strip() or len(text) > MAX_TEXT:
        raise ProposalError(400, f"body.text must be a non-empty string under {MAX_TEXT} chars")
    cand = parse(text)
    turn = re.search(r"^\s*turn:\s*(\d+)", text, re.M)
    return render(cand, "operator", session_id, int(turn.group(1)) if turn else 0)


def decide(session_id: str, pid: str, decision: str, text: Any, cwd: str, *, seen: Any,
           hooks: Any = None, emit: Callable[[str, dict[str, Any]], None] | None = None,
           ) -> dict[str, Any]:
    """Apply approve, edit or reject to one proposal; the ``memory_decided`` payload.

    ``seen`` is the sha256 of the proposal text the operator was shown.
    """
    if decision not in ("approve", "edit", "reject"):
        raise ProposalError(400, "body.decision must be approve, edit or reject")
    path = _proposal_path(session_id, pid)
    if not isinstance(seen, str) or seen != digest(path.read_text(encoding="utf-8")):
        raise ProposalError(409, "the proposal changed since it was shown; reload it")
    out: dict[str, Any] = {"id": pid, "decision": decision}
    if decision == "reject":
        path.unlink()
    else:
        body = _edited(text, session_id) if decision == "edit" else path.read_text(encoding="utf-8")
        if decision == "edit":
            path.write_text(body, encoding="utf-8")
        out["path"] = str(_land(session_id, body, cwd, hooks))
        path.unlink()
    if emit is not None:
        emit("memory_decided", out)
    return out
